name: build-test feature branch
# TODO maybe we want to have different actions for feature / develop / master branches
on: [push]
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '6.10.3'
      - run: cd frontend
      - run: npm install
      - run: npm install -g bower
      - run: bower install

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd backend
      - run: ls -la
