name: build-test new feature branch
# TODO maybe we want to have different actions for feature / develop / master branches
on: [push]
jobs:
  build-test frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '6.10.3'
      - run: npm install
      - run: npm install -g bower
      - run: bower install

  build-test backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - run: cd backend
      - run: ls -la
