name: build-test new feature branch
on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'
jobs:
  build-test_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '6.10.3'
      - run: npm install -g
      - run: npm install -g bower
      - run: bower install

      # TODO: run, test, build

  build-test_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.3.1'
      - run: echo 'gem: –no-ri –no-rdoc' > ~/.gemrc
      - run: bundle install --without production -j5 --retry 10
      - run: cp env-example .env
      - run: bundle exec rake app:setup
      - run: rake run

      # TODO: test
