name: build & test new feature branch
on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    defaults:
      run:
        working-directory: backend

    services:
      mongo:
        image: mongo:3.0.10
        ports:
          - 27017:27017

      postgres:
        image: postgres:9.4
        ports:
          - 5432:5432

      redis:
        image: redis:3.2.6
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '6.10.3'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.3.1'

      - name: Configure Ruby
        run: 'echo "gem: --no-ri --no-rdoc" > ~/.gemrc'

      - name: Install System Dependencies
        run: sudo apt-get install libssl1.0 postgresql-client

      - name: Install Frontend Dependencies
        run: |
          npm install -g
          npm install -g bower
          bower install
        working-directory: frontend

      - name: Install Backend Dependencies
        run: bundle install --without production -j5

      - name: Build & Run
        run: |
          cp env-example .env
          bundle exec rake app:setup
          rake run

      - name: Test The Build
        run: echo "TODO"

  create-pull-request:
    needs: build-and-test
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          pr_title: "Pulling ${{ github.ref }} into develop"
          pr_body: ":crown: *Automated Pull Request After Feature Branch Passed All Tests*"
          github_token: ${{ secrets.GITHUB_TOKEN }}
