name: build-test new feature branch
on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'
jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '6.10.3'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.3.1'

      - name: Configuring Ruby
        run: 'echo "gem: --no-ri --no-rdoc" > ~/.gemrc'

      - name: Install System Dependencies
        run: sudo apt-get install libssl1.0

      - name: Install Frontend Dependencies
        run: |
          npm install -g
          npm install -g bower
          bower install
        working-directory: frontend

      # TODO: run, test, build frontend

      - name: Install Backend Dependencies
        run: bundle install --without production -j5

      - name: Build And Run Backend
        run: |
          cp env-example .env
          bundle exec rake app:setup
          rake run

      # TODO: test backend
