name: build-test new feature branch
on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'
jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '6.10.3'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.3.1'

      - name: Configure Ruby
        run: 'echo "gem: --no-ri --no-rdoc" > ~/.gemrc'

      - name: Install System Dependencies
        run: sudo apt-get install libssl1.0

      - name: Install Frontend Dependencies
        run: |
          echo "TODO"
          echo "remove comments"
        #  npm install -g
        #  npm install -g bower
        #  bower install
        working-directory: frontend

      - name: Build & Run Frontend
        run: echo "TODO"
        working-directory: frontend

      - name: Install Backend Dependencies
        run: bundle install --without production -j5

      - name: Build & Run Backend
        run: |
          cp env-example .env
        #  bundle exec rake app:setup
        #  rake run

      - name: Test Build
        run: echo "TODO"

  create-pull-request:
    needs: build-test
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          pr_title: "Pulling ${{ github.ref }} into develop"
          pr_body: ":crown: *Automated Pull Request After Feature Branch Passed All Tests*"
          github_token: ${{ secrets.GITHUB_TOKEN }}
